# Generated by Django 5.1.4 on 2025-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketch_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sketch',
            name='sketch_image',
            field=models.ImageField(blank=True, null=True, upload_to='sketches/'),
        ),
    ]
