# Generated by Django 5.2.1 on 2025-05-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketch_api', '0002_sketch_processed_sketch_sketch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='style',
            field=models.CharField(choices=[('sketch', 'Sketch'), ('ghibli', 'Ghibli Style')], default='sketch', max_length=20),
        ),
    ]
